//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokenizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPESOUTIEN
    {
        public decimal Id { get; set; }
        public string libelle { get; set; }
        public Nullable<decimal> multiplicateur { get; set; }
    }
}
