//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokenizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int ID_USER { get; set; }
        public string NAME { get; set; }
        public string FIRSTNAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public string EMAIL { get; set; }
    }
}
